### ISSUE TITLE
INFO: Definición del formato del JSON para Visualización-Resultados

### ISSUE THREAD

**Issue by valbarsau** [AgoraUS1516/G06#3]
Buenas, somos el equipo de trabajo de Visualización y Frontend Resultados. Seria recomendable que definieseis el formato de JSON que comentamos en sesiones anteriores con el objetivo de poder realizar una simulación (stub) para poder continuar con el desarrollo de nuestro subsistema y poder tener en cuenta los cambios que van a tener lugar en el de Recuento.

**Comment by DavidGG11** [comment]
El formato que se define para el JSON de cada clase es el siguiente:

Votaciones
{{"id":"XXX","title":"XXX","description":"XXX","startDate":"XXX","endDate":"XXX","questions":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"}]}

Preguntas
{{"id":"XXX","title":"XXX","textQuestion":"XXX","options":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"}]}

Opciones
{{"id":"XXX","title":"XXX","minOptions":"XXX","maxOption":"XXX"}

**Comment by danmarrod** [comment]
Buenas, respecto al formato que indicais, de cara a la mejora teneis planeado modificarlo? Es para trabajar sobre ese formato o adaptarnos al nuevo ahora que estamos a tiempo.

Un saludo, gracias.

**Comment by DavidGG11** [comment]
Buenas, mañana nos reuniremos los de nuestro grupo para tratar sobre ese tema, ya que tres miembros de los cuatro tenemos mañana MSN, y no hemos podido analizar aún nada. Cuando sepamos algo, te digo. Perdón por las molestias.

**Comment by DavidGG11** [comment]
En cuanto al formato de JSON, esperamos resolverlo lo antes posible, ya que aún dudamos en algunos atributos.

**Comment by DavidGG11** [comment]
El formato que se define para el JSON de cada clase es el siguiente, finalmente se ha eliminado el atributo _"Options"_ ya que venía comentado en el código original, pero sin embargo no a la hora de convertir a JSON, espero que no os resulte una molestia:

Votaciones
{{"id":"XXX","title":"XXX","description":"XXX","startDate":"XXX","endDate":"XXX","questions":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"}]}

Preguntas
{{"id":"XXX","title":"XXX","textQuestion":"XXX"}
