### ISSUE TITLE
Definir el formato JSON

### ISSUE THREAD

**Issue by Adrianelcio10** [AgoraUS1516/G06#4]
Definir el formato JSON para nuestro subsistema

**Comment by danperrod** [comment]
Deberías detallar un poco más la incidencia. Podrías incluir una captura del formato que suelen los archivos JSON, los atributos que quieres que tenga, etc.

**Comment by Adrianelcio10** [comment]
Por ejemplo, para una votación sería algo asi:
{{"id":"XXX","title":"XXX","description":"XXX","startDate":"XXX","endDate":"XXX","questions":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"]}

**Comment by danperrod** [comment]
De acuerdo. El formato que se define para el JSON de cada clase es el siguiente:
- Votaciones
  {{"id":"XXX","title":"XXX","description":"XXX","startDate":"XXX","endDate":"XXX","questions":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"}]}
- Preguntas
  {{"id":"XXX","title":"XXX","textQuestion":"XXX","options":[{"id":"XXX","text":"XXX"},{"id":"XXX","text":"XXX"}]}
- Opciones
  {{"id":"XXX","title":"XXX","minOptions":"XXX","maxOption":"XXX"}
